### PR TITLE
convert makrdown link to slack link

### LINKED ISSUE #37: styling of links
we're using markdown styling that slack doesn't understand. looks like the URLs should be formatted like this? could we quickly change that? note how the links are set up using <> instead of []

{
  "type": "section",
  "text": {
    "type": "mrkdwn",
    "text": "New Paid Time Off request from <[example.com](http://example.com/)|Fred Enriquez>\n\n<https://example.com/|View request>"
  }
}

### PR DESCRIPTION
**Pull request by 20001LastOrder**
Convert the markdown-styled link to slack style link.

resolve #37

### CODE REVIEW

**Review by saminegash — DISMISSED** [review]
LGTM

**Comment by 20001LastOrder** [comment]
@Eyobyb  Can you take a look and approve this?

**Review by Eyobyb — DISMISSED** [review]

**Comment by 20001LastOrder** [comment]
@Eyobyb @saminegash, I resolved the merge conflict and formated the file. Please take a look again

**Review by saminegash — APPROVED** [review]
lgtm

**Pull request merged**
