### PR TITLE
Update bolt_app.py for verbose message output

### PR DESCRIPTION
**Pull request by johnnykfeng**
created `get_response_v2( )` to get the verbose output from the bot

replaced `get_response` with `get_response_v2` inside `def event_test(client, say, event)`

### CODE REVIEW

**Comment by 20001LastOrder** [comment]
I'm not sure replacing one function with another function call is a good idea, though... Maybe remove the ond get_response and change the verbose as a parameter to the function call so that it can be configured to give either verbose or not verbose output?

**Comment by johnnykfeng** [comment]
okay, I did it this way to preserve the old function, but I can just replace np

**Comment by 20001LastOrder** [comment]
This should address #31

**Comment by 20001LastOrder** [comment]
> Okay, I did it this way to preserve the old function in case we want to change it back, but I can just replace easily it if that's makes it more clear.
Please do so, we can always rely on the commit history if something went wrong :)

**Comment by johnnykfeng** [comment]
@20001LastOrder made a new commit based on suggestions, please check them out when you have time

**Review by 20001LastOrder — APPROVED** [review]
LGTM

**Pull request merged**
